#!/usr/bin/env ruby
#
# named by "Yoshihiro Ura <support@fuuzu.net>" - https://github.com/kyubuns/

class Header
  def initialize(hb)
    raise "magic mismatch" unless hb[257, 5] == 'ustar'

    @name = hb[0, 100].rstrip
      .gsub(/[^[:print:]]/) {|m| '#'}
      .gsub(/\//, '+')
      .gsub(/^\./, '_')
    @size = hb[124, 12].oct
    @type = hb[156]
  end

  def name() @name end
  def size() @size end
  def type() @type end

  def dirname() "" end
  def basename() name end

  def self.find_next(inb, unit = 512)
    while true
      block = inb.read(unit)
      return nil if block == nil

      i = block.index("ustar")
      return nil if i == nil
      return Header.new(block) if i == 257

      puts "info: Index of magic mismatched, try to reindexing..."
      inb.seek(-(unit + 257 - i), IO::SEEK_CUR)
    end
  end
end

File.open(ARGV[0], 'rb') {|inb|
  while true
    h = Header.find_next(inb)
    break if h == nil

    File.open(h.name, 'wb') {|outb|
      done = outb.write(inb.read(h.size))
      puts "written #{h.name}"
      puts "   warning: #{h.size} bytes expected but written #{done} bytes..." if h.size != done
    }
  end
}
