#!/bin/sh
# Thanks to Federico
# https://people.gnome.org/~federico/blog/alt-tab.html
set -e
gsettings set org.gnome.desktop.wm.keybindings switch-applications "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-applications-backward "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Alt>Tab', '<Super>Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward  "['<Alt><Shift>Tab', '<Super><Shift>Tab']"
gsettings set org.gnome.shell.window-switcher current-workspace-only true
